version: 2
updates:
  # Enable version updates for Java
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps(maven): "
    labels:
      - "dependencies"
    open-pull-requests-limit: 5

  # Enable version updates for the go client
  - package-ecosystem: "gomod"
    directory: "clients/go"
    schedule:
      interval: "daily"
    commit-message:
      # "deps(clients/go): " is too long
      prefix: "deps(go): "
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "github.com/docker/*"

  # Enable version updates for the github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps(.github): "
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
